### ISSUE TITLE
Проблема установки модуля Futag с помощью pip

### ISSUE THREAD

**Issue by CourteousSleet** [ispras/Futag#58]
При попытке установки модуля Futag на системе Debian столкнулся с подобной ошибкой.
```
ian@mn4-fuzz-dev:~ pip install ./futag-llvm/python-package/futag-1.3.tar.gz 
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 223, in _main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 317, in run
    reqs = self.get_requirements(args, options, finder, session)
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 368, in get_requirements
    for parsed_req in parse_requirements(
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_file.py", line 151, in parse_requirements
    for parsed_line in parser.parse(filename, constraint):
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_file.py", line 341, in parse
    for line in self._parse_and_recurse(filename, constraint):
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_file.py", line 346, in _parse_and_recurse
    for line in self._parse_file(filename, constraint):
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_file.py", line 379, in _parse_file
    _, content = get_file_content(filename, self._session)
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_file.py", line 569, in get_file_content
    content = auto_decode(f.read())
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/encoding.py", line 39, in auto_decode
    return data.decode(
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

```

**Comment by thientc** [comment]
А вам именно 1.3 нужна? Или можно [1.3.1.](https://github.com/ispras/Futag/releases/tag/1.3.1) попробовать?

**Comment by CourteousSleet** [comment]
Для 1.3.1 устанавливается.
