### ISSUE TITLE
Возможно ошибка размещения llvm после последнего коммита

### ISSUE THREAD

**Issue by DmitryJustDmitry** [ispras/Futag#6]
Не получается запустить тестовый срипт сборки и анализа.

1. Скрипт выглядит так:

```python
from futag.preprocessor import *

json0_13 = Builder(
    "/Futag/futag-llvm-package/", # path to the futag-llvm-package
    "/Futag/json-c" # library root
)
json0_13.auto_build()
json0_13.analyze()
```

2. Вот так выглядит структура каталогов после сборки llvm и установки futag посредством pip:

```bash
root@2bf92881f9c9:/Futag# pwd
/Futag
root@2bf92881f9c9:/Futag# tree -L 2 -d
.
|-- build
|   |-- CMakeFiles
|   |-- benchmarks
|   |-- bin
|   |-- cmake
|   |-- docs
|   |-- examples
|   |-- include
|   |-- lib
|   |-- libexec
|   |-- projects
|   |-- runtimes
|   |-- share
|   |-- test
|   |-- tools
|   |-- unittests
|   `-- utils
|-- custom-llvm
|   |-- clang
|   |-- compiler-rt
|   `-- llvm
|-- futag-llvm-package
|   |-- python
|   `-- svres-tmpl
|-- json-c
|   |-- apps
|   |-- bench
|   |-- cmake
|   |-- doc
|   |-- fuzz
|   `-- tests
|-- src
|   |-- Checkers
|   |-- clang
|   |-- python
|   `-- svres-tmpl
`-- vendors
    |-- deb-rdepend-downloader
    `-- json-3.10.5

39 directories
root@2bf92881f9c9:/Futag# ll
total 108
drwxr-xr-x  9 root root  4096 Jul 28 11:04 ./
drwxr-xr-x  1 root root  4096 Jul 28 10:45 ../
-rw-r--r--  1 root root 12288 Jul 28 11:04 .build.py.swp
drwxr-xr-x  8 root root  4096 Jul 28 10:45 .git/
-rw-r--r--  1 root root   203 Jul 28 10:45 .gitignore
-rw-r--r--  1 root root   417 Jul 28 10:45 CHANGELOG.md
-rw-r--r--  1 root root 35149 Jul 28 10:45 LICENSE
-rw-r--r--  1 root root  3718 Jul 28 10:45 README.en.md
-rw-r--r--  1 root root  6236 Jul 28 10:45 README.md
drwxr-xr-x 18 root root  4096 Jul 28 10:47 build/
-rw-r--r--  1 root root   199 Jul 28 11:04 build.py
drwxr-xr-x  5 root root  4096 Jul 28 10:46 custom-llvm/
drwxr-xr-x  4 root root  4096 Jul 28 10:51 futag-llvm-package/
drwxr-xr-x 10 root root  4096 Jul 28 10:52 json-c/
drwxr-xr-x  6 root root  4096 Jul 28 10:45 src/
drwxr-xr-x  4 root root  4096 Jul 28 10:45 vendors/
```

3. При попытке запуска тестового скрипта (я назвал его build.py) выводится вот такая ошибка:

```bash
root@2bf92881f9c9:/Futag# python3 build.py
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    json0_13 = Builder(
  File "/usr/local/lib/python3.8/dist-packages/futag/preprocessor.py", line 81, in __init__
    raise ValueError(INVALID_FUTAG_PATH, futag_llvm_package)
ValueError: ('-- [Futag]: Incorrect path to FUTAG llvm package', '/Futag/futag-llvm-package/')
```

4. Пробовал "поиграть" путями - не смог подобрать пути, чтобы скрипт запустился.

**Comment by thientc** [comment]
Я исправил в последнем коммите, проверьте пожалуйста!

**Comment by DmitryJustDmitry** [comment]
Починилось!

**Comment by bbuklov** [comment]
Добрый день! Столкнулся с похожей проблемой. Futag не может найти файл bin/clang в директории инструмента Futag (в моем случае - `futag-llvm`, как описано в readme).

Ниже привожу листинг директории Futag:
```
bbuklov@Precision-Tower:~/Futag$ tree -L 2 -d
.
├── build
│   ├── bin
│   ├── cmake
│   ├── CMakeFiles
│   ├── include
│   ├── lib
│   ├── libexec
│   ├── projects
│   ├── runtimes
│   ├── share
│   ├── tools
│   └── utils
├── custom-llvm
│   └── llvm-project
├── examples
├── futag-llvm
│   ├── AFLplusplus
│   ├── AFLplusplus-4.02c
│   ├── python-package
│   └── svres-tmpl
├── product-tests
│   ├── build-test
│   ├── libraries-test
│   └── package-test
├── src
│   ├── Checkers
│   ├── clang
│   ├── python
│   └── svres-tmpl
└── vendors
    ├── deb-rdepend-downloader
    └── json-3.10.5

32 directories
bbuklov@Precision-Tower:~/Futag$ find . -type f -name "clang"
./custom-llvm/llvm-project/clang/test/Tooling/Inputs/mock-libcxx/bin/clang
./custom-llvm/llvm-project/clang-tools-extra/test/clang-tidy/infrastructure/Inputs/mock-libcxx/bin/clang
bbuklov@Precision-Tower:~/Futag$ 
```
А также тестовый скрипт запуска ():
```
from futag.preprocessor import *

FUTAG_PATH = "/mnt/sdc/bbuklov/projects/Futag/futag-llvm"
lib_path = "/mnt/sdc/bbuklov/projects/test-packages/bash/bash-5.1"
build_test = Builder(
    FUTAG_PATH,
    lib_path,
    clean=True, # удалить все папки сгенерированные Futag-ом перед сборкой
    # intercept=True, # запуск компиляции с инструментом "intercept" для анализа compile_command.json
    # processes=4, # количество задач при сборке
    # build_ex_params="--with-openssl --with-mhash" # дополнительные параметры при сборке библиотеки
)
build_test.auto_build()
build_test.analyze()
```

Текст ошибки следующий:
```
bbuklov@Precision-Tower:~/Futag$ python3 build.py 
-- [Futag]: Incorrect path to FUTAG llvm package/mnt/sdc/bbuklov/projects/Futag/futag-llvm
```
