### ISSUE TITLE
Ошибка выполнения в последнем релизе

### ISSUE THREAD

**Issue by CourteousSleet** [ispras/Futag#78]
Поставил свежий релиз 2-0-4.
С пользовательскими флагами компиляциями и с теми, что стоят по умолчанию в процессе компиляции получаю одну и ту же ошибку:
````
-- [Futag] Try to generate fuzz-driver for function:  pg_fe_scram_exchange ...
Traceback (most recent call last):
  File "/home/sedley/Work/Development/alabamian-trakt/fuzzing.futag.libpq.std-11-cert.res/libpq/scripts/build.py", line 17, in <module>
    g.compile_targets(flags='-fsanitize=address,fuzzer -g -O0 -fprofile-instr-generate -fcoverage-mapping')#, coverage=True)
  File "/home/sedley/.local/lib/python3.10/site-packages/futag/generator.py", line 2587, in compile_targets
    current_include.append("-I" + i + "/")
TypeError: can only concatenate str (not "PosixPath") to str
````

````
-- [Futag] Try to generate fuzz-driver for function:  pg_fe_scram_exchange ...
Traceback (most recent call last):
  File "/home/sedley/Work/Development/alabamian-trakt/fuzzing.futag.libpq.std-11-cert.res/libpq/scripts/build.py", line 17, in <module>
    g.compile_targets()
  File "/home/sedley/.local/lib/python3.10/site-packages/futag/generator.py", line 2587, in compile_targets
    current_include.append("-I" + i + "/")
TypeError: can only concatenate str (not "PosixPath") to str
````

**Comment by thientc** [comment]
Здесь флаг `fuzzer` лишний?
